
export default function fixedDates(year) {

    function isLeapYear(year) {
        return (year % 4 === 0 && year % 100 !== 0) || (year % 400 === 0);
    }

    const data=[
        {
            month:'January - The Holy Name of Jesus',
            details:[
                {
                    date:`${year}-01-01`,
                    feast:`The Octave-Day of the Nativity of the Lord.\nCircumcision of the Lord.`,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-01-02`,
                    feast:``,
                    saint:`St. Basil the Great, Gregory Nazianzen - Bishop, St. Marcarius`,
                    color:`White`,
                },
                {
                    date:`${year}-01-03`,
                    feast:``,
                    saint:`The Most Holy Name of Jesus`,
                    color:`White`,
                },
                {
                    date:`${year}-01-04`,
                    feast:``,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-01-05`,
                    feast:``,
                    saint:`St. Telesphorus`,
                    color:`White`,
                },
                {
                    date:`${year}-01-06`,
                    feast:`The Epiphany of the Lord`,
                    saint:`St. Melchior, St. Baldastar***`,
                    color:`White`,
                },
                {
                    date:`${year}-01-07`,
                    feast:`The Holy Family of Jesus, Mary & Joseph`,
                    saint:`St. Lucian`,
                    color:`White`,
                },
                {
                    date:`${year}-01-08`,
                    feast:``,
                    saint:`St. Appomaris***`,
                    color:`White`,
                },
                {
                    date:`${year}-01-09`,
                    feast:``,
                    saint:`St. Julian, St. Adrian`,
                    color:`White`,
                },
                {
                    date:`${year}-01-10`,
                    feast:`Nyabinga - Anton Ooro's home - wealth brought by Baba Messiah.\nBaba Messiah the Worker`,
                    saint:`St. Nicanor, St. William`,
                    color:`Purple`,
                },
                {
                    date:`${year}-01-11`,
                    feast:``,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-01-12`,
                    feast:``,
                    saint:`St. Marguerite, St. Benedict Biscop`,
                    color:`White`,
                },
                {
                    date:`${year}-01-13`,
                    feast:`The Baptism of Our Lord Jesus Christ`,
                    saint:`St. Hilary - Bishop`,
                    color:`White`,
                },
                {
                    date:`${year}-01-14`,
                    feast:``,
                    saint:`St. Malachias, St. Felix of Nola - Priest & Martyr`,
                    color:`Red`,
                },
                {
                    date:`${year}-01-15`,
                    feast:``,
                    saint:`St. Maurus - Abbot, St. Paul the Hermit - Confessor`,
                    color:`White`,
                },
                {
                    date:`${year}-01-16`,
                    feast:``,
                    saint:`St. Marcellus - Pope & Martyr`,
                    color:`Red`,
                },
                {
                    date:`${year}-01-17`,
                    feast:``,
                    saint:`St. Sulpice, St. Anthony - Abbot`,
                    color:`White`,
                },
                {
                    date:`${year}-01-18`,
                    feast:`Chair of St. Peter at Rome`,
                    saint:`St. Paul & Prisca - Virgin & Martyr`,
                    color:`White`,
                },
                {
                    date:`${year}-01-19`,
                    feast:``,
                    saint:`St. Marius, Martha, Audifax, Abachum - Martyrs, St. Canute - King & Martyr`,
                    color:`Red`,
                },
                {
                    date:`${year}-01-20`,
                    feast:``,
                    saint:`St. Fabian - Pope & St. Sabastian - Martyrs `,
                    color:`Red`,
                },
                {
                    date:`${year}-01-21`,
                    feast:``,
                    saint:`St. Agnes - Virgin & Martyr`,
                    color:`Red`,
                },
                {
                    date:`${year}-01-22`,
                    feast:``,
                    saint:`St. Vincent & Anastasius - Martyrs`,
                    color:`Red`,
                },
                {
                    date:`${year}-01-23`,
                    feast:``,
                    saint:`St. Raymond of Pennafort - confessor, St. Emerentiana - Virgin & Martyr`,
                    color:`White`,
                },
                {
                    date:`${year}-01-24`,
                    feast:``,
                    saint:`St. Timothy - Bishop & Martyr `,
                    color:`Red`,
                },
                {
                    date:`${year}-01-25`,
                    feast:`Baba Simeo's Accident, Mawego Kobuya Kendu Bay Diocese.\nThe Conversion of St. Paul, Apostle`,
                    saint:`St. Peter - Apostle`,
                    color:`Purple`,
                },
                {
                    date:`${year}-01-26`,
                    feast:``,
                    saint:`St. Paula St. Polycarp - Bishop & Martyr`,
                    color:`Red`,
                },
                {
                    date:`${year}-01-27`,
                    feast:``,
                    saint:`St. John Chrysostom - Bishop`,
                    color:`White`,
                },
                {
                    date:`${year}-01-28`,
                    feast:``,
                    saint:`St. Peter Nolasco, St. Thomas Aquinas`,
                    color:`White`,
                },
                {
                    date:`${year}-01-29`,
                    feast:``,
                    saint:`St. Francis de Sales - Bishop`,
                    color:`White`,
                },
                {
                    date:`${year}-01-30`,
                    feast:``,
                    saint:`St. Martina - Virgin & Martyr`,
                    color:`Red`,
                },
                {
                    date:`${year}-01-31`,
                    feast:``,
                    saint:`St. John Bosco - Confessor`,
                    color:`White`,
                },
            ]
        },
        {
            month:'February - The Holy Family',
            details:[
                {
                    date:`${year}-02-01`,
                    feast:``,
                    saint:`St. Ignatius - Bishop & Martyr `,
                    color:`Red`,
                },
                {
                    date:`${year}-02-02`,
                    feast:`The Purification of the Blessed Virgin Mary`,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-02-03`,
                    feast:``,
                    saint:`St. Blaise - Bishop & Martyr`,
                    color:`Red`,
                },
                {
                    date:`${year}-02-04`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-02-05`,
                    feast:``,
                    saint:`St. Agatha - Virgin & Martyr`,
                    color:`Red`,
                },
                {
                    date:`${year}-02-06`,
                    feast:``,
                    saint:`St. Titus - Bishop of Crete & Confessor, St. Dorothy - Virgin & Martyr`,
                    color:`White`,
                },
                {
                    date:`${year}-02-07`,
                    feast:``,
                    saint:`St. Romuald - Abbot`,
                    color:`White`,
                },
                {
                    date:`${year}-02-08`,
                    feast:``,
                    saint:`St. John of Matha - Confessor`,
                    color:`White`,
                },
                {
                    date:`${year}-02-09`,
                    feast:``,
                    saint:`St. Cyril, Bishop of Alexandria, St. Apollonia - Virgin & Martyr`,
                    color:`White`,
                },
                {
                    date:`${year}-02-10`,
                    feast:``,
                    saint:`St. Scholastica - Virgin `,
                    color:`White`,
                },
                {
                    date:`${year}-02-11`,
                    feast:``,
                    saint:`Our Lady of Lourdes`,
                    color:`White`,
                },
                {
                    date:`${year}-02-12`,
                    feast:``,
                    saint:`The Seven Holy Founders of the Servite Order - Confessors`,
                    color:`White`,
                },
                {
                    date:`${year}-02-13`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-02-14`,
                    feast:``,
                    saint:`St. Valentine - Priest & Martyr`,
                    color:`Red`,
                },
                {
                    date:`${year}-02-15`,
                    feast:``,
                    saint:`St. Faustinus & Jovita, Martyrs`,
                    color:`Red`,
                },
                {
                    date:`${year}-02-16`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-02-17`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-02-18`,
                    feast:``,
                    saint:`St. Simeon - Bishop`,
                    color:`White`,
                },
                {
                    date:`${year}-02-19`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-02-20`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-02-21`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-02-22`,
                    feast:`The Chair of St. Peter at Antioch`,
                    saint:`St. Paul, Apostle`,
                    color:`White`,
                },
                {
                    date:`${year}-02-23`,
                    feast:``,
                    saint:`St. Peter Damian - Bishop & Confessor.`,
                    color:`White`,
                },
                {
                    date:`${year}-02-24`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-02-25`,
                    feast:``,
                    saint:`St. Mathias - Apostle `,
                    color:`White`,
                },
                {
                    date:`${year}-02-26`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-02-27`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-02-28`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                
            ]
        },
        {
            month:'March - St. Joseph',
            details:[
                {
                    date:`${year}-03-01`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-02`,
                    feast:`Persecution of Legion Maria, Kirindo/Jerusalem`,
                    color:`Purple`,
                },
                {
                    date:`${year}-03-03`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-04`,
                    feast:``,
                    saint:`St. Casimir - Confessor, St. Lucius - Pope & Martyr`,
                    color:`Red`,
                },
                {
                    date:`${year}-03-05`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-06`,
                    feast:``,
                    saint:`St. Perpetua & Felicity, Martyrs`,
                    color:`Red`,
                },
                {
                    date:`${year}-03-07`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-08`,
                    feast:``,
                    saint:`St. John of God - Confessor`,
                    color:`White`,
                },
                {
                    date:`${year}-03-09`,
                    feast:``,
                    saint:`St. Frances of Rome - Widow`,
                    color:`White`,
                },
                {
                    date:`${year}-03-10`,
                    feast:``,
                    saint:`Forty Martyrs of Sebaste`,
                    color:`Red`,
                },
                {
                    date:`${year}-03-11`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-12`,
                    feast:``,
                    saint:`St. Gregory - Pope`,
                    color:`White`,
                },
                {
                    date:`${year}-03-13`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-14`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-15`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-16`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-17`,
                    feast:``,
                    saint:`St. Patrick - Bishop`,
                    color:`White`,
                },
                {
                    date:`${year}-03-18`,
                    feast:``,
                    saint:`St. Cyril - Bishop of Jerusalem`,
                    color:`White`,
                },
                {
                    date:`${year}-03-19`,
                    feast:``,
                    saint:`St. Joseph - Spouse of the Blessed Virgin Mary & Confessor `,
                    color:`White`,
                },
                {
                    date:`${year}-03-20`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-21`,
                    feast:``,
                    saint:`St. Benedict - Abbot`,
                    color:`White`,
                },
                {
                    date:`${year}-03-22`,
                    feast:`The Seven Sorrows of the Blessed Virgin Mary`,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-03-23`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-24`,
                    feast:``,
                    saint:`St. Gabriel the Archangel`,
                    color:`White`,
                },
                {
                    date:`${year}-03-25`,
                    feast:`The Annunciation of the Blessed Virgin Mary (Acies)`,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-03-26`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-27`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-28`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-29`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-30`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-03-31`,
                    feast:``,
                    saint:``,
                    color:``,
                },
            ]
        },
        {
            month:'April - The Blessed Sacrament',
            details:[
                {
                    date:`${year}-04-01`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-04-02`,
                    feast:``,
                    saint:`St. Mary`,
                    color:`White`,
                },
                {
                    date:`${year}-04-03`,
                    feast:``,
                    saint:`St. Richard`,
                    color:`White`,
                },
                {
                    date:`${year}-04-04`,
                    feast:``,
                    saint:`St. Isidore - Bishop, St. Benedict`,
                    color:`White`,
                },
                {
                    date:`${year}-04-05`,
                    feast:``,
                    saint:`St. Vincent Ferrer`,
                    color:`White`,
                },
                {
                    date:`${year}-04-06`,
                    feast:``,
                    saint:`St. Juliana`,
                    color:`White`,
                },
                {
                    date:`${year}-04-07`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-04-08`,
                    feast:``,
                    saint:`St. Julie Billiart`,
                    color:`White`,
                },
                {
                    date:`${year}-04-09`,
                    feast:`Legion Maria/African Pentecost`,
                    saint:`St. Mary of Cleophas`,
                    color:`Red`,
                },
                {
                    date:`${year}-04-10`,
                    feast:``,
                    saint:``,
                    color:`Red`,
                },
                {
                    date:`${year}-04-11`,
                    feast:``,
                    saint:`St. Leo the Great - Pope`,
                    color:`White`,
                },
                {
                    date:`${year}-04-12`,
                    feast:``,
                    saint:`St. Sabbas`,
                    color:`White`,
                },
                {
                    date:`${year}-04-13`,
                    feast:``,
                    saint:`St. Hermenegild - Martyr`,
                    color:`Red`,
                },
                {
                    date:`${year}-04-14`,
                    feast:``,
                    saint:`St. Justin - Martyr, St. Velerian, St. Tiburtius, St. Maximus`,
                    color:`Red`,
                },
                {
                    date:`${year}-04-15`,
                    feast:``,
                    saint:`St. Anastasia, St. Basilissa****`,
                    color:`White`,
                },
                {
                    date:`${year}-04-16`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-04-17`,
                    feast:``,
                    saint:`St. Anicetus - Pope & Martyr`,
                    color:`White`,
                },
                {
                    date:`${year}-04-18`,
                    feast:``,
                    saint:`St. Apedle****`,
                    color:`White`,
                },
                {
                    date:`${year}-04-19`,
                    feast:``,
                    saint:`St. Leo IX`,
                    color:`White`,
                },
                {
                    date:`${year}-04-20`,
                    feast:``,
                    saint:`St. Marcellinus`,
                    color:`White`,
                },
                {
                    date:`${year}-04-21`,
                    feast:``,
                    saint:`St. Anselm`,
                    color:`White`,
                },
                {
                    date:`${year}-04-22`,
                    feast:``,
                    saint:`St. Soter & Cajus - Popes & Martyrs `,
                    color:`Red`,
                },
                {
                    date:`${year}-04-23`,
                    feast:``,
                    saint:`St. George - Martyr `,
                    color:`Red`,
                },
                {
                    date:`${year}-04-24`,
                    feast:``,
                    saint:`St. Fidelis of Sigmaringen - Martyr`,
                    color:`Red`,
                },
                {
                    date:`${year}-04-25`,
                    feast:`The Greater Litanies.\nRogation Day`,
                    saint:`St. Mark - Evangelist. `,
                    color:`White`,
                },
                {
                    date:`${year}-04-26`,
                    feast:``,
                    saint:`St. Cletus & Marcellinus - Popes & Martyrs`,
                    color:`Red`,
                },
                {
                    date:`${year}-04-27`,
                    feast:``,
                    saint:`St. Peter Canisius - Confessor, St. Zita`,
                    color:`White`,
                },
                {
                    date:`${year}-04-28`,
                    feast:``,
                    saint:`St. Paul of the Cross, St. Vitalis - Martyr, St. Louis Marie de Montfort.`,
                    color:`Red`,
                },
                {
                    date:`${year}-04-29`,
                    feast:``,
                    saint:`St. Peter Verona - Martyr.`,
                    color:`Red`,
                },
                {
                    date:`${year}-04-30`,
                    feast:``,
                    saint:`St. Catherine of Siena - Virgin.`,
                    color:`White`,
                },
                
            ]
        },
        {
            month:'May - The Blessed Virgin Mary',
            details:[
                {
                    date:`${year}-05-01`,
                    feast:``,
                    saint:`St. Joseph the Worker - Spouse of the Blessed Virgin Mary & Confessor. St. Peregrine`,
                    color:`White`,
                },
                {
                    date:`${year}-05-02`,
                    feast:``,
                    saint:`St. Athanasius - Bishop`,
                    color:`White`,
                },
                {
                    date:`${year}-05-03`,
                    feast:``,
                    saint:`St. Philip & James - Apostles. St. Alexander, Eventius & Theodulus - Martyrs, Juvenal & Bishop. St. Timothy & Maura.`,
                    color:`Red`,
                },
                {
                    date:`${year}-05-04`,
                    feast:``,
                    saint:`St. Monica.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-05`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-05-06`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-05-07`,
                    feast:``,
                    saint:`St. Stanislaus.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-08`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-05-09`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-05-10`,
                    feast:``,
                    saint:`St. Antonius.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-11`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-05-12`,
                    feast:``,
                    saint:`St. Achilles. St. Nereus. St. Pancratius.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-13`,
                    feast:``,
                    saint:`St. Robert Bellarmine.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-14`,
                    feast:``,
                    saint:`St. Boniface. St. Matthias.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-15`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-05-16`,
                    feast:``,
                    saint:`St. Brendan. St. Simon Stock. St. Ubaldus.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-17`,
                    feast:``,
                    saint:`St. Paschal Baylon. St. Patrick.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-18`,
                    feast:``,
                    saint:`St. Venantius.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-19`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-05-20`,
                    feast:``,
                    saint:`St. Bernardine.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-21`,
                    feast:``,
                    saint:`St. Andrew Bobola.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-22`,
                    feast:``,
                    saint:`St. Rita.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-23`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-05-24`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-05-25`,
                    feast:``,
                    saint:`St. Madeleine Sophie.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-26`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-05-27`,
                    feast:``,
                    saint:`St. Bede - Venerable.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-28`,
                    feast:``,
                    saint:`St. Augustine.`,
                    color:`White`,
                },
                {
                    date:`${year}-05-29`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-05-30`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-05-31`,
                    feast:`Feast of the Visitation`,
                    saint:``,
                    color:`White`,
                },
                
            ]
        },
        {
            month:'June - The Sacred Heart of Jesus',
            details:[
                {
                    date:`${year}-12-01`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-02`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-03`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-04`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-05`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-06`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-07`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-08`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-09`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-10`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-11`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-12`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-13`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-14`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-15`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-16`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-17`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-18`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-19`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-20`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-21`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-22`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-23`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-24`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-25`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-26`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-27`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-28`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-29`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-30`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                
                
            ]
        },
        {
            month:'July - The Precious Blood',
            details:[
                {
                    date:`${year}-12-01`,
                    feast:`Feast of the Most Precious Blood`,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-12-02`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-03`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-04`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-05`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-06`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-07`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-08`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-09`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-10`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-11`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-12`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-13`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-14`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-15`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-16`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-17`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-18`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-19`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-20`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-21`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-22`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-23`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-24`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-25`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-26`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-27`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-28`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-29`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-30`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-31`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                
            ]
        },
        {
            month:'August - The Immaculate Heart of Mary',
            details:[
                {
                    date:`${year}-12-01`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-02`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-03`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-04`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-05`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-06`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-07`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-08`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-09`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-10`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-11`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-12`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-13`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-14`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-15`,
                    feast:`Solemnity of the Assumption of the Blessed Virgin Mary`,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-12-16`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-17`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-18`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-19`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-20`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-21`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-22`,
                    feast:`Feast of the Queenship of Mary`,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-12-23`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-24`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-25`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-26`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-27`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-28`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-29`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-30`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-31`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                
            ]
        },
        {
            month:'September - The Seven Sorrows of Mary',
            details:[
                {
                    date:`${year}-12-01`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-02`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-03`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-04`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-05`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-06`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-07`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-08`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-09`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-10`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-11`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-12`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-13`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-14`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-15`,
                    feast:`The feast of Our Lady of Sorrows`,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-12-16`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-17`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-18`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-19`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-20`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-21`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-22`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-23`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-24`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-25`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-26`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-27`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-28`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-29`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-30`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                
                
            ]
        },
        {
            month:'October - The Holy Rosary',
            details:[
                {
                    date:`${year}-12-01`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-02`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-03`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-04`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-05`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-06`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-07`,
                    feast:`Feast of Our Lady of the Rosary`,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-12-08`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-09`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-10`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-11`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-12`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-13`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-14`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-15`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-16`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-17`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-18`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-19`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-20`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-21`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-22`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-23`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-24`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-25`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-26`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-27`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-28`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-29`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-30`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-31`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                
            ]
        },
        {
            month:'November - The Holy Souls in Purgatory',
            details:[
                {
                    date:`${year}-12-01`,
                    feast:`All Saints`,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-12-02`,
                    feast:`Commemoration of All Souls`,
                    saint:``,
                    color:`Black`,
                },
                {
                    date:`${year}-12-03`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-04`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-05`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-06`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-07`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-08`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-09`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-10`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-11`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-12`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-13`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-14`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-15`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-16`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-17`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-18`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-19`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-20`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-21`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-22`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-23`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-24`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-25`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-26`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-27`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-28`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-29`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-30`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                
                
            ]
        },
        {
            month:'December - The Immaculate Conception',
            details:[
                {
                    date:`${year}-12-01`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-02`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-03`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-04`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-05`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-06`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-07`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-08`,
                    feast:`The Solemnity of the Immaculate Conception`,
                    saint:``,
                    color:`White`,
                },
                {
                    date:`${year}-12-09`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-10`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-11`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-12`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-13`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-14`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-15`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-16`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-17`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-18`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-19`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-20`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-21`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-22`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-23`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-24`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-25`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-26`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-27`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-28`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-29`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-30`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                {
                    date:`${year}-12-31`,
                    feast:``,
                    saint:``,
                    color:``,
                },
                
            ]
        },
    ]

    if (isLeapYear(year)) {
        data[1].details.push({
            date: `${year}-02-29`,
            feast: ``,
            saint: ``,
            color: ``
        });
    }

    return data

}

export function fixedSundayFeasts() {

    const ashWednesdayDates=[
        '2023-02-22',
        '2024-02-14',
        '2025-03-05',
        '2026-02-18',
        '2027-02-10',
        '2028-03-01',
        '2029-02-14',
        '2030-03-06',
        '2031-02-26',
        '2032-02-11',
        '2033-03-02',
    ]

    const data1=[
        {
            feast:`1st Sunday after Epiphany.`,
            color:`White`,
        },
        {
            feast:`2nd Sunday After Epiphany.`,
            color:`Green`,
        },
        {
            feast:`3rd Sunday after Epiphany.`,
            color:`Green`,
        },
        {
            feast:`4th Sunday after Epiphany.`,
            color:`Green`,
        },
        {
            feast:`5th Sunday after Epiphany.`,
            color:`Green`,
        },
        {
            feast:`6th Sunday after Epiphany.`,
            color:`Green`,
        },
        {
            feast:`7th Sunday after Epiphany.`,
            color:`Green`,
        },
        {
            feast:`8th Sunday after Epiphany.`,
            color:`Green`,
        },
        {
            feast:`9th Sunday after Epiphany.`,
            color:`Green`,
        },
        {
            feast:`10th Sunday after Epiphany.`,
            color:`Green`,
        },
        
    ]

    const data2=[
        
        {
            feast:`Septuagesima.`,
            color:`Purple`,
        },
        {
            feast:`Sexagesima.`,
            color:`Purple`,
        },
        {
            feast:`Quinquagesima.`,
            color:`Purple`,
        },
    ]

    const data3=[
        
        {
            feast:`First Sunday of Lent.`,
            color:`Purple`,
        },
        {
            feast:`Second Sunday of Lent.`,
            color:`Purple`,
        },
        {
            feast:`Third Sunday of Lent.`,
            color:`Purple`,
        },
        {
            feast:`Fourth Sunday of Lent (Laetare).`,
            color:`Rose/White`,
        },
        {
            feast:`Passion Sunday.`,
            color:`Purple`,
        },
        {
            feast:`Palm Sunday.`,
            color:`Red/Purple`,
        },
        {
            feast:`Easter Sunday.`,
            color:`White`,
        },
    ]

    const data4=[
        
        {
            feast:`Solemn Easter Vigil and First Mass of Easter Sunday.`,
            color:`Purple`,
        },
        {
            feast:`Good Friday.`,
            color:`Black/Purple`,
        },
        {
            feast:`Holy Thursday.`,
            color:`Purple/White`,
        }
        
    ]

    return {data1, data2, data3, data4, ashWednesdayDates}

}